name: Test Container

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ifox6677/padavan-ng:master  # 确保使用正确的镜像路径和标签
      credentials:
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_PAT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test container
        run: |
          echo "Container is running"
          uname -a
          # 运行一些基本命令以确认环境
